# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Ci

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # stpe1 : Check out the code from the  repository
    - name: Check out code
      uses: actions/checkout@v4

    # stpe2 : Set up Python 3.10 envivonment
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    # stpe3 : Install dependencies, run tests and lint with flake8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt; fi

    # stpe4 : Run tests 
    - name: run test
      run: pytest
       